# platform :ios, '14.0'

pod 'CapacitorStorage', '~> 1.2.0'
pod 'CapacitorCamera', '~> 1.3.0'
pod 'CapacitorFilesystem', '~> 1.1.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            # config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
    end
end
