import { optionsBuilder } from '../helpers/helpers';
import { isAndroid } from '@nativescript/core';

export function popupHandler(popupOptions) {
	const popup = isAndroid ? new com.highsoft.highcharts.common.hichartsclasses.HIPopup() : new HIPopup();

	const popupSchema = {
		addButton: 'string',
		arrowLine: 'string',
		arrowRay: 'string',
		arrowSegment: 'string',
		background: 'string',
		backgroundColor: 'string',
		backgroundColors: 'string',
		borderColor: 'string',
		borderRadius: 'string',
		borderWidth: 'string',
		circle: 'string',
		color: 'string',
		connector: 'string',
		crooked3: 'string',
		crooked5: 'string',
		crosshairX: 'string',
		crosshairY: 'string',
		editButton: 'string',
		elliott3: 'string',
		elliott5: 'string',
		fibonacci: 'string',
		fill: 'string',
		flags: 'string',
		fontSize: 'string',
		format: 'string',
		height: 'string',
		horizontalLine: 'string',
		infinityLine: 'string',
		innerBackground: 'string',
		label: 'string',
		labelOptions: 'string',
		labels: 'string',
		line: 'string',
		lines: 'string',
		measure: 'string',
		measureX: 'string',
		measureXY: 'string',
		measureY: 'string',
		name: 'string',
		outerBackground: 'string',
		padding: 'string',
		parallelChannel: 'string',
		pitchfork: 'string',
		ray: 'string',
		rectangle: 'string',
		removeButton: 'string',
		saveButton: 'string',
		segment: 'string',
		series: 'string',
		shapeOptions: 'string',
		shapes: 'string',
		simpleShapes: 'string',
		stroke: 'string',
		strokeWidth: 'string',
		style: 'string',
		title: 'string',
		tunnel: 'string',
		typeOptions: 'string',
		verticalArrow: 'string',
		verticalCounter: 'string',
		verticalLabel: 'string',
		verticalLine: 'string',
		volume: 'string',
	};

	return optionsBuilder(popupSchema, popupOptions, popup);
}
